<?php

namespace app\index\controller;

use app\common\controller\HomeBase;
use app\common\model\OrderCharging;
use app\common\model\OrderCharging as OrderChargingModel;

class Charging extends HomeBase
{
    private $order_charging_model;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->order_charging_model = new OrderChargingModel();
    }

    public function index()
    {
        exit('非法入侵');
    }

    /**
     * 启动充电桩
     * @param $cid
     * @param $gid
     * @param $key
     */
    public function start_order($cid = '', $gid = '', $key = '')
    {
        $data_temp = $this->request->param();
        file_put_contents('ctem.txt', json_encode($data_temp));
        $out_data['code'] = 0;
        $out_data['info'] = "参数有误";
        if ($key == 'cdz2018ycdl') {
            if ($this->order_charging_model->acquireOrder($cid, $gid)) {
                $out_data['code'] = 1;
                $out_data['info'] = "启动成功";
                out_json_data($out_data);
            }
            $out_data['info'] = "启动失败";
            out_json_data($out_data);
        }
        out_json_data($out_data);
    }

    /**
     * 停止充电桩
     * @param $id
     * @param $energy
     * @param $key
     */
    public function end_order($id = '', $energy = '0.1', $key = '')
    {
        $out_data['code'] = 0;
        $out_data['info'] = "参数有误";
        $data_temp = $this->request->param();
        file_put_contents('cend.txt', json_encode($data_temp));
        if ($key == 'cdz2018ycdl') {
            if ($this->order_charging_model->returnOrder($id, floatval($energy))) {
                $out_data['code'] = 1;
                $out_data['info'] = "停止成功";
                out_json_data($out_data);
            }
            $out_data['info'] = "停止失败";
            out_json_data($out_data);
        }
        out_json_data($out_data);
    }
}
