SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `ycdl_order_analyze_201808`;
CREATE TABLE `ycdl_order_analyze_201808` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '订单索引id',
  `store_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '卖家店铺id',
  `store_name` varchar(50) NOT NULL COMMENT '卖家店铺名称',
  `customer_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '买家id',
  `customer_phone` varchar(20) DEFAULT NULL COMMENT '电话号码',
  `customer_name` varchar(50) DEFAULT NULL COMMENT '买家用户名/电话号码',
  `payment_code` char(50) CHARACTER SET utf8 NOT NULL DEFAULT '' COMMENT '支付方式名称代码 alipay支付宝 weixin微信 unionpay 银联',
  `payment_time` int(10) unsigned DEFAULT '0' COMMENT '支付(付款)时间',
  `order_amount` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '订单总价格',
  `goods_id` int(11) DEFAULT '0' COMMENT '商品id',
  `goods_device` varchar(100) DEFAULT NULL COMMENT '设备号',
  `goods_name` varchar(100) DEFAULT NULL COMMENT '商品名称',
  `goods_type` int(11) DEFAULT '1' COMMENT '商品类型 1普通汽车 2纯电动车 3充电桩',
  `goods_licence_plate` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `acquire_time` int(10) DEFAULT '0' COMMENT '取用时间',
  `acquire_month` varchar(8) DEFAULT NULL COMMENT '取车月（年-月）',
  `acquire_date` varchar(10) DEFAULT NULL COMMENT '取车日期（年-月-日）',
  `acquire_hour` tinyint(2) DEFAULT '0' COMMENT '取车小时（24小时）',
  `acquire_week` tinyint(2) DEFAULT '0' COMMENT '星期几 0星期天 ',
  `acquire_address` text COMMENT '取用地址 序列化数据 name 地址名称 local 地址坐标',
  `acquire_store_id` int(11) DEFAULT '0' COMMENT '取车门店id',
  `acquire_store_name` varchar(100) DEFAULT NULL COMMENT '取用门店名称',
  `return_time` int(10) DEFAULT '0' COMMENT '归还时间',
  `return_month` varchar(8) DEFAULT NULL COMMENT '还车时间（年-月）',
  `return_date` varchar(10) DEFAULT NULL COMMENT '取车日期（年-月-日）',
  `return_hour` tinyint(2) DEFAULT '0' COMMENT '还车时间（24小时）',
  `return_week` tinyint(2) DEFAULT '0' COMMENT '星期几 0星期天',
  `year_week` varchar(10) DEFAULT NULL COMMENT '还车日期（年-周）',
  `all_mileage` int(8) DEFAULT '0' COMMENT '总里程',
  `reality_return_time` int(10) DEFAULT '0' COMMENT '实际归还时间',
  `return_address` text COMMENT '归还地址 序列化数据 name 地址名称 local 地址坐标',
  `return_store_id` int(11) DEFAULT '0' COMMENT '还车门店id',
  `return_store_name` varchar(100) DEFAULT NULL COMMENT '退还门店名称',
  `order_status` tinyint(4) unsigned zerofill NOT NULL DEFAULT '0010' COMMENT '订单状态：0(已取消)10(默认):未付款，20:已付款，30:已取商品，40:归还商品，50:订单完成，60:已退款',
  `channel_uid` varchar(20) DEFAULT '0' COMMENT '分销渠道推广用户id',
  `store_key_id` int(11) DEFAULT '0' COMMENT '数据归属店铺id',
  `store_key_name` varchar(100) DEFAULT NULL COMMENT '总店铺名称',
  PRIMARY KEY (`id`),
  KEY `id` (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';